name: allthenews
description: Combined news from different apis
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.0.0
  cupertino_icons: ^0.1.2
  get_it: ^4.0.2
  webview_flutter: ^1.0.7
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3
  package_info: ^0.4.1
  flutter_svg: ^0.18.0
  moor: ^3.4.0
  moor_ffi: ^0.8.0
  rxdart: ^0.24.1
  intl: ^0.16.1

  # Networking
  json_annotation: ^3.0.1
  connectivity: ^2.0.2
  dio: ^3.0.9
  pretty_dio_logger: ^1.1.1

  # Firebase
  firebase_crashlytics: ^0.2.3
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1

  #Location
  google_maps_flutter: ^1.0.6
  geolocator: ^6.1.13

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  build_runner: ^1.8.0
  moor_generator: ^3.3.1
  json_serializable: ^3.2.5
  lint: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - auth/secrets.json
    - assets/
  fonts:
    - family: Chomsky
      fonts:
        - asset: assets/fonts/Chomsky.otf
        - asset: assets/images/news.svg
flutter_intl:
  enabled: true
  class_name: Strings
